version: "3.7"

services:
  service:
    build: "./service" 
    ports:
      - 8080:8080 
    depends_on:
      - db
    links:
      - db      

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - "./database/data:/var/lib/postgresql/data"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - db
    links:
      - db